server:
  port: 8083

sa-token:
  token-name: token
  timeout: 3600
  active-timeout: -1
  is-concurrent: false
  token-style: uuid
  is-log: true

spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 102400MB
      max-request-size: 10240000MB

privateKey: "MIICeAIBADANBgkqhkiG9w0BAQEFAASCAmIwggJeAgEAAoGBAOK3yzyKpk+fc5nfGZrNIakETTUGXs2jGNGRvI8jM249EIADrkNfbl+BqTu8FdifiITZePPYPLAnpcSiyiIY/Qapj50MTcRkxrA9kVWX8B8QyacuEJWUEIlsnymVTzFlm2GiUhEyCGtfUdS94APH7eU+WH4CiVg/59YTTbyDZnpBAgMBAAECgYEAhvRGy0PxGaZdprNRx37h0X0ZBD5FgnzaUi1BI6cdfzpkLv+B5OLSjZFeDou4KVlVZ1cYk3YdMfJ3z2PjlIZxXj23kdOrUWHO3QAtXEpGGfsPKH7I6xJQ7BL/cFnXx/ldIc1i2taHHBPYgogQBPxVcgmNzCYh6e8YNNar2KHX+RECQQD9MKB228N23eYcqXzSi3wtp4vDetzYCUsJs75PhX8i79hdIm3jWWvSxUFQtECu2gTQlAMG2RjS0jh/y0zK1OfVAkEA5Tv0K12Wj5uw4HE5dILDDDtQzPaiRuRjlp0YpTwmVtJxVZZgA/kCiP6+U6I0MII0k5fpWqgurDFUD2MgPAUKvQJBAJPHiiFV7CS5J9Ka6oxJddV/8YfLcpN1+SJUk0P++1H9BCB4NAN68gA3ugPM8eQcxKqpeYrJtD95DBkrJEtPMXECQGsj/XhzUpamdyI/6VG6eD10T8ysjaZCwwU3QbihB25XB5+wHApfTT8IiZ5/VpNBmB9PxkKYDtBucdKLSxqiZKUCQQC9HQRAFyCdVwWQmNgu8NS3S8Ok3Ds3TaGuU+R35kdCm6muxGodLOGm5kH6Upc+g+M8OOqVfpSR9T2sRztENxuV"
publicKey: "MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDit8s8iqZPn3OZ3xmazSGpBE01Bl7NoxjRkbyPIzNuPRCAA65DX25fgak7vBXYn4iE2Xjz2DywJ6XEosoiGP0GqY+dDE3EZMawPZFVl/AfEMmnLhCVlBCJbJ8plU8xZZtholIRMghrX1HUveADx+3lPlh+AolYP+fWE028g2Z6QQIDAQAB"
