spring:
  file-storage:
    default-platform: local-plus-1
    thumbnail-suffix: ".min.jpg"
    local-plus:
      - platform: local-plus-1
        enable-storage: true  #启用存储
        enable-access: true
        domain: http://localhost:8083/local-plus/
        base-path:
        path-patterns: /local-plus/**
        storage-path: D:/JavaProjects/SaToken/file/
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/file?useUnicode=true&characterEncoding=utf-8&userSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
